# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionBuildinTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.IntegerField()),
                ('action', models.CharField(max_length=32)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'collection_buildin_task',
            },
        ),
        migrations.CreateModel(
            name='CollectionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('url_field', models.CharField(max_length=128)),
                ('data_format', models.CharField(max_length=32)),
                ('time_interval', models.FloatField()),
            ],
            options={
                'db_table': 'collection_source',
            },
        ),
        migrations.CreateModel(
            name='CollectionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('progress', models.CharField(max_length=32)),
                ('begin_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'collection_task',
            },
        ),
        migrations.CreateModel(
            name='CollectionTaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('progress', models.CharField(max_length=32)),
                ('begin_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'collection_task_history',
            },
        ),
    ]
